kind: Deployment
apiVersion: apps/v1
metadata:
  name: camunda-deployment
  namespace: camunda
  labels:
    app: camunda
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: camunda
  template:
    metadata:
      labels:
        app: camunda
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
        consul.hashicorp.com/connect-service-upstreams: 'counting:9001'
    spec:
      containers:
        - name: camunda
          image: camunda/camunda-bpm-platform:latest
          ports:
            - containerPort: 8080
              protocol: TCP