kind: Service
apiVersion: v1
metadata:
  name: camunda
  labels:
    app: camunda
  namespace: camunda
spec:
  selector:
    app: camunda
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer