global:
  name: consul
  gossipEncryption: 
    secretName: consul-gossip-encryption-key
    secretKey: key
server:
  replicas: 1
  storageClass: openebs-jiva-default
  bootstrapExpect: 1
  exposeGossipAndRPCPorts: true
    serflan:
      port: 9301
ui:
  service:
    type: LoadBalancer
connectInject:
  enabled: false
  default: false
client:
  enable: false
  exposeGossipPorts: false
controller:
  enabled: false