global:
  name: consul
  gossipEncryption: 
    secretName: consul-gossip-encryption-key
    secretKey: key
  enableConsulNamespaces: true
server:
  replicas: 1
  storageClass: openebs-jiva-default
  bootstrapExpect: 1
  disruptionBudget:
    enabled: true
    maxUnavailable: 0
ui:
  service:
    type: LoadBalancer
connectInject:
  enabled: true
  default: true
  consulNamespaces:
    mirroringK8S: true
    mirroringK8SPrefix: 'k8s-'
client:
  enable: true
controller:
  enabled: true