kind: ConfigMap
apiVersion: v1
metadata:
  name: config
  namespace: metallb-system
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 10.8.0.100-10.8.0.250
---
kind: Secret
apiVersion: v1
metadata:
  name: memberlist
  namespace: metallb-system
data:
  secretkey: >-
    UmljZTFzdkxGYkVlME11WEV2T3VxVHR5VFZQUEt5b1B5V2ZSNjlReWQ3NmVnblJFRzlkSVBxNm8rZUxrQmZlNgpZQk9wbElKenpyczJyTThycGFWQUFhWVZ4QVNDVHZOSEJHZDB5UEFBNVZuM0gwRFhTK0JnQ0dtdUlHWnIva283CkFvZklKekpiUGhKU01PR01za1JZYlp5Q3RXRmlSQklwL2hvTFhLVllCT2s9
type: Opaque