pvcStorageClassName: openebs-jiva-default
elasticsearch:
  enabled: true
  volumeClaimTemplate: 
    storageClassName: openebs-jiva-default
    resources:
      requests:
        storage: 10Gi
  resources:
    requests:
      cpu: 100m
      memory: 2Gi
    limits:
      cpu: 1000m
      memory: 2Gi
  replicas: 1
  minimumMasterNodes: 1
resources:
  requests:
    cpu: 100m
    memory: 1Gi
  limits:
    cpu: 1000m
    memory: 1Gi