pvcStorageClassName: openebs-jiva-default
elasticsearch:
  enabled: true
  volumeClaimTemplate: 
    storageClassName: openebs-jiva-default
    resources:
      requests:
        storage: 5Gi
  resources:
    requests:
      cpu: "100m"
      memory: "512M"
    limits:
      cpu: "1000m"
      memory: "512M"
  replicas: 1
  minimumMasterNodes: 1
clusterSize: 1
partitionCount: 1